from odoo import api, fields, models, _

class Periodontal(models.Model):
	_name = 'periodontal'

	diente11 = fields.Text() #Usar para diccionarios 
	diente12 = fields.Text()
	diente13 = fields.Text()
	diente14 = fields.Text()
	diente15 = fields.Text()
	diente16 = fields.Text()
	diente17 = fields.Text()
	diente18 = fields.Text()	
	d11 = fields.Boolean() # SUPERIOR Dientes izquieda
	d12 = fields.Boolean()
	d13 = fields.Boolean()
	d14 = fields.Boolean()
	d15 = fields.Boolean()
	d16 = fields.Boolean()
	d17 = fields.Boolean()
	d18 = fields.Boolean()
	# Implante
	i11 = fields.Boolean()
	i12 = fields.Boolean()
	i13 = fields.Boolean()
	i14 = fields.Boolean()
	i15 = fields.Boolean()
	i16 = fields.Boolean()
	i17 = fields.Boolean()
	i18 = fields.Boolean()
	# Movilidad
	m11 = fields.Char()
	m12 = fields.Char()
	m13 = fields.Char()
	m14 = fields.Char()
	m15 = fields.Char()
	m16 = fields.Char()
	m17 = fields.Char()
	m18 = fields.Char()
	# Pronostico individual
	pi11 = fields.Char()
	pi12 = fields.Char()
	pi13 = fields.Char()
	pi14 = fields.Char()
	pi15 = fields.Char()
	pi16 = fields.Char()
	pi17 = fields.Char()
	pi18 = fields.Char()
	# Furca
	f16 = fields.Selection([
		('0','0'),	
		('1','1'),	
		('2','2'),	
		('3','3'),	
	],)
	f17 = fields.Selection([
		('0','0'),	
		('1','1'),	
		('2','2'),	
		('3','3'),	
	],)
	f18 = fields.Selection([
		('0','0'),	
		('1','1'),	
		('2','2'),	
		('3','3'),	
	],)
	# Sangrado
	sa11 = fields.Boolean()
	sa12 = fields.Boolean()
	sa13 = fields.Boolean()
	sa14 = fields.Boolean()
	sa15 = fields.Boolean()
	sa16 = fields.Boolean()
	sa17 = fields.Boolean()
	sa18 = fields.Boolean()
	sb11 = fields.Boolean()
	sb12 = fields.Boolean()
	sb13 = fields.Boolean()
	sb14 = fields.Boolean()
	sb15 = fields.Boolean()
	sb16 = fields.Boolean()
	sb17 = fields.Boolean()
	sb18 = fields.Boolean()
	sc11 = fields.Boolean()
	sc12 = fields.Boolean()
	sc13 = fields.Boolean()
	sc14 = fields.Boolean()
	sc15 = fields.Boolean()
	sc16 = fields.Boolean()
	sc17 = fields.Boolean()
	sc18 = fields.Boolean()
# Placa
	pa11 = fields.Boolean()
	pa12 = fields.Boolean()
	pa13 = fields.Boolean()
	pa14 = fields.Boolean()
	pa15 = fields.Boolean()
	pa16 = fields.Boolean()
	pa17 = fields.Boolean()
	pa18 = fields.Boolean()
	pb11 = fields.Boolean()
	pb12 = fields.Boolean()
	pb13 = fields.Boolean()
	pb14 = fields.Boolean()
	pb15 = fields.Boolean()
	pb16 = fields.Boolean()
	pb17 = fields.Boolean()
	pb18 = fields.Boolean()
	pc11 = fields.Boolean()
	pc12 = fields.Boolean()
	pc13 = fields.Boolean()
	pc14 = fields.Boolean()
	pc15 = fields.Boolean()
	pc16 = fields.Boolean()
	pc17 = fields.Boolean()
	pc18 = fields.Boolean()
# Anchura encia
	ae11 = fields.Char()
	ae12 = fields.Char()
	ae13 = fields.Char()
	ae14 = fields.Char()
	ae15 = fields.Char()
	ae16 = fields.Char()
	ae17 = fields.Char()
	ae18 = fields.Char()

# Margen gingival
	mga11 = fields.Char()
	mga12 = fields.Char()
	mga13 = fields.Char()
	mga14 = fields.Char()
	mga15 = fields.Char()
	mga16 = fields.Char()
	mga17 = fields.Char()
	mga18 = fields.Char()
	mgb11 = fields.Char()
	mgb12 = fields.Char()
	mgb13 = fields.Char()
	mgb14 = fields.Char()
	mgb15 = fields.Char()
	mgb16 = fields.Char()
	mgb17 = fields.Char()
	mgb18 = fields.Char()
	mgc11 = fields.Char()
	mgc12 = fields.Char()
	mgc13 = fields.Char()
	mgc14 = fields.Char()
	mgc15 = fields.Char()
	mgc16 = fields.Char()
	mgc17 = fields.Char()
	mgc18 = fields.Char()
# Profundidad de sondaje
	psa11 = fields.Char()
	psa12 = fields.Char()
	psa13 = fields.Char()
	psa14 = fields.Char()
	psa15 = fields.Char()
	psa16 = fields.Char()
	psa17 = fields.Char()
	psa18 = fields.Char()
	psb11 = fields.Char()
	psb12 = fields.Char()
	psb13 = fields.Char()
	psb14 = fields.Char()
	psb15 = fields.Char()
	psb16 = fields.Char()
	psb17 = fields.Char()
	psb18 = fields.Char()
	psc11 = fields.Char()
	psc12 = fields.Char()
	psc13 = fields.Char()
	psc14 = fields.Char()
	psc15 = fields.Char()
	psc16 = fields.Char()
	psc17 = fields.Char()
	psc18 = fields.Char()
	# Dientes derecha
	d11 = fields.Boolean()
	d12 = fields.Boolean()
	d13 = fields.Boolean()
	d14 = fields.Boolean()
	d15 = fields.Boolean()
	d16 = fields.Boolean()
	d17 = fields.Boolean()
	d18 = fields.Boolean()
